development:
  adapter: postgresql
  encoding: unicode
  database: db8hbf3ielifdd
  host: ec2-54-243-42-236.compute-1.amazonaws.com
  username: ubkrnilgvyesza
  password: Ac9UDBYu9nZLMWDRHLs4SHqZJf
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: db8hbf3ielifdd
  host: ec2-54-243-42-236.compute-1.amazonaws.com
  username: ubkrnilgvyesza
  password: Ac9UDBYu9nZLMWDRHLs4SHqZJf
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: db8hbf3ielifdd
  host: ec2-54-243-42-236.compute-1.amazonaws.com
  username: ubkrnilgvyesza
  password: Ac9UDBYu9nZLMWDRHLs4SHqZJf
  port: 5432

